// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqeRC9WkbRdqxmkhQFWCiKDPa9qEICCaA',
    appId: '1:1043466156262:web:baacfc567b5dbd0942a327',
    messagingSenderId: '1043466156262',
    projectId: 'aria-fe980',
    authDomain: 'aria-fe980.firebaseapp.com',
    storageBucket: 'aria-fe980.appspot.com',
    measurementId: 'G-QZQF04NNEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFE_o-Vw3CNDa6Dcp621lTApECUWWUm0s',
    appId: '1:1043466156262:android:4f5922645ec53c4e42a327',
    messagingSenderId: '1043466156262',
    projectId: 'aria-fe980',
    storageBucket: 'aria-fe980.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpmYgi_wvcCu7l6uXUiRR3V8UncUJNGhA',
    appId: '1:1043466156262:ios:2f130a5e70a027fa42a327',
    messagingSenderId: '1043466156262',
    projectId: 'aria-fe980',
    storageBucket: 'aria-fe980.appspot.com',
    iosBundleId: 'com.example.aria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpmYgi_wvcCu7l6uXUiRR3V8UncUJNGhA',
    appId: '1:1043466156262:ios:977aef1047e1d50e42a327',
    messagingSenderId: '1043466156262',
    projectId: 'aria-fe980',
    storageBucket: 'aria-fe980.appspot.com',
    iosBundleId: 'com.example.aria.RunnerTests',
  );
}
